---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      initContainers:
      - name: helloworld-migrations
        securityContext:
          allowPrivilegeEscalation: false
        image: golang:alpine
        envFrom:
        - configMapRef:
            name: helloworld-env
        - secretRef:
            name: helloworld-postgres-env
        volumeMounts:
          - mountPath: /migrations
            name: migrations
        command:
          - sh
          - "-c"
          - |
            go install github.com/jackc/tern@latest
            tern migrate --migrations /migrations
      containers:
      - name: helloworld
        securityContext:
          allowPrivilegeEscalation: false
        image: helloworld:latest
        envFrom:
        - configMapRef:
            name: helloworld-env
        - secretRef:
            name: helloworld-postgres-env
        readinessProbe:
          grpc:
            port: 41888
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          grpc:
            port: 41888
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: migrations
        configMap:
          name: helloworld-migrations
